<?php

session_start();

if (!isset($_SESSION["username"])) {
    echo "Bitte erst <a href=\"index.php\">einloggen</a>";
    exit;
}

$mysqli = new mysqli('localhost', $_SESSION["username"], $_SESSION["password"], 'LIMET_RB');
if ($mysqli->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

/* change character set to utf8 */
if (!$mysqli->set_charset("utf8")) {
    echo "Error loading character set utf8: " . $mysqli->error;
    exit();
}


$sql = "INSERT INTO `LIMET_RB`.`tabelle_räume`
    (`Raumnr`,
    `Raumbezeichnung`,
    `TABELLE_Funktionsteilstellen_idTABELLE_Funktionsteilstellen`,
    `tabelle_projekte_idTABELLE_Projekte`,
    `MT-relevant`,
    `Funktionelle Raum Nr`,
    `Raumnummer_Nutzer`,
    `Raumbereich Nutzer`,
    `Geschoss`,
    `Bauetappe`,
    `Bauabschnitt`,
    `Nutzfläche`,
    `Abdunkelbarkeit`,
    `Strahlenanwendung`,
    `Laseranwendung`,
    `H6020`,
    `GMP`,
    `ISO`,
    `1 Kreis O2`,
    `2 Kreis O2`,
    `O2`,
    `1 Kreis Va`,
    `2 Kreis Va`,
    `VA`,
    `1 Kreis DL-5`,
    `2 Kreis DL-5`,
    `DL-5`,
    `DL-10`,
    `DL-tech`,
    `CO2`,
    `H2`,
    `He`,
    `He-RF`,
    `Ar`,
    `N2`,
    `NGA`,
    `N2O`,
    `AV`,
    `SV`,
    `ZSV`,
    `USV`,
    `IT Anbindung`,
    `Anwendungsgruppe`,
    `Allgemeine Hygieneklasse`,
    `Raumhoehe`,
    `Raumhoehe 2`,
    `Belichtungsfläche`,
    `Umfang`,
    `Volumen`,
    `ET_Anschlussleistung_W`,
    `HT_Waermeabgabe_W`,
    `VEXAT_Zone`,
    `HT_Abluft_Vakuumpumpe`,
    `HT_Abluft_Schweissabsaugung_Stk`,
    `HT_Abluft_Esse_Stk`,
    `HT_Abluft_Rauchgasabzug_Stk`,
    `HT_Abluft_Digestorium_Stk`,
    `HT_Punktabsaugung_Stk`,
    `HT_Abluft_Sicherheitsschrank_Unterbau_Stk`,
    `HT_Abluft_Sicherheitsschrank_Stk`,
    `HT_Spuele_Stk`,
    `HT_Kühlwasser`,
    `O2_Mangel`,
    `CO2_Melder`,
    `ET_RJ45-Ports`,
    `ET_64A_3Phasig_Einzelanschluss`,
    `ET_32A_3Phasig_Einzelanschluss`,
    `ET_16A_3Phasig_Einzelanschluss`,
    `ET_Digestorium_MSR_230V_SV_Stk`,
    `ET_5x10mm2_Digestorium_Stk`,
    `ET_5x10mm2_USV_Stk`,
    `ET_5x10mm2_SV_Stk`,
    `ET_5x10mm2_AV_Stk`,
    `Wasser Qual 3 l/min`,
    `Wasser Qual 2 l/Tag`,
    `Wasser Qual 1 l/Tag`,
    `Wasser Qual 3`,
    `Wasser Qual 2`,
    `Wasser Qual 1`,
    `LHe`,
    `LN l/Tag`,
    `LN`,
    `N2 Reinheit`,
    `N2 l/min`,
    `Ar Reinheit`,
    `Ar l/min`,
    `He Reinheit`,
    `He l/min`,
    `H2 Reinheit`,
    `H2 l/min`,
    `DL ISO 8573`,
    `DL l/min`,
    `VA l/min`,
    `CO2 l/min`,
    `CO2 Reinheit`,
    `O2 l/min`,
    `O2 Reinheit`,
    `Laserklasse`,      
    `ET_Anschlussleistung_AV_W`,
    `ET_Anschlussleistung_SV_W`,
    `ET_Anschlussleistung_ZSV_W`,
    `ET_Anschlussleistung_USV_W`,
    `EL_AV Steckdosen Stk`,
    `EL_SV Steckdosen Stk`,
    `EL_ZSV Steckdosen Stk`,
    `EL_USV Steckdosen Stk`,
    `EL_Roentgen 16A CEE Stk` )
    VALUES
    ('" . filter_input(INPUT_GET, 'raumnummer') . "',
    '" . filter_input(INPUT_GET, 'raumbezeichnung') . "',
    '" . filter_input(INPUT_GET, 'funktionsteilstelle') . "',
    " . $_SESSION["projectID"] . ",
    '" . filter_input(INPUT_GET, 'MTrelevant') . "',
    '" . filter_input(INPUT_GET, 'funktionelleraumnr') . "',
    '" . filter_input(INPUT_GET, 'raumnummernutzer') . "',
    '" . filter_input(INPUT_GET, 'raumbereichnutzer') . "',
    '" . filter_input(INPUT_GET, 'geschoss') . "',
    '" . filter_input(INPUT_GET, 'bauetappe') . "',
    '" . filter_input(INPUT_GET, 'bauabschnitt') . "',
    '" . filter_input(INPUT_GET, 'nutzfläche') . "',
    '" . filter_input(INPUT_GET, 'abdunkelbarkeit') . "',
    '" . filter_input(INPUT_GET, 'strahlenanwendung') . "',
    '" . filter_input(INPUT_GET, 'laseranwendung') . "',
    '" . filter_input(INPUT_GET, 'h6020') . "',
    '" . filter_input(INPUT_GET, 'gmp') . "',
    '" . filter_input(INPUT_GET, 'iso') . "',
    '" . filter_input(INPUT_GET, '_1kreiso2') . "',
    '" . filter_input(INPUT_GET, '_2kreiso2') . "',
    '" . filter_input(INPUT_GET, 'o2') . "',
    '" . filter_input(INPUT_GET, '_1kreisva') . "',
    '" . filter_input(INPUT_GET, '_2kreisva') . "',
    '" . filter_input(INPUT_GET, 'va') . "',
    '" . filter_input(INPUT_GET, '_1kreisdl5') . "',
    '" . filter_input(INPUT_GET, '_2kreisdl5') . "',
    '" . filter_input(INPUT_GET, 'dl5') . "',
    '" . filter_input(INPUT_GET, 'dl10') . "',
    '" . filter_input(INPUT_GET, 'dltech') . "',
    '" . filter_input(INPUT_GET, 'co2') . "',
    '" . filter_input(INPUT_GET, 'h2') . "',
    '" . filter_input(INPUT_GET, 'he') . "',
    '" . filter_input(INPUT_GET, 'herf') . "',
    '" . filter_input(INPUT_GET, 'ar') . "',
    '" . filter_input(INPUT_GET, 'n2') . "',
    '" . filter_input(INPUT_GET, 'nga') . "',
    '" . filter_input(INPUT_GET, 'n2o') . "',
    '" . filter_input(INPUT_GET, 'av') . "',
    '" . filter_input(INPUT_GET, 'sv') . "',
    '" . filter_input(INPUT_GET, 'zsv') . "',
    '" . filter_input(INPUT_GET, 'usv') . "',
    '" . filter_input(INPUT_GET, 'itanbindung') . "',
    '" . filter_input(INPUT_GET, 'anwendungsgruppe') . "',
    '" . filter_input(INPUT_GET, 'allgemeinehygieneklasse') . "',
    '" . filter_input(INPUT_GET, 'raumhoehe') . "',
    '" . filter_input(INPUT_GET, 'raumhoehe2') . "',
    '" . filter_input(INPUT_GET, 'belichtungsfläche') . "',
    '" . filter_input(INPUT_GET, 'umfang') . "',
    '" . filter_input(INPUT_GET, 'volumen') . "',
    '" . filter_input(INPUT_GET, 'etanschlussleistungw') . "',
    '" . filter_input(INPUT_GET, 'htwaermeabgabew') . "',
    '" . filter_input(INPUT_GET, 'vexatzone') . "',
    '" . filter_input(INPUT_GET, 'htabluftvakuumpumpe') . "',
    '" . filter_input(INPUT_GET, 'htabluftschweissabsaugungstk') . "',
    '" . filter_input(INPUT_GET, 'htabluftessestk') . "',
    '" . filter_input(INPUT_GET, 'htabluftrauchgasabzugstk') . "',
    '" . filter_input(INPUT_GET, 'htabluftdigestoriumstk') . "',
    '" . filter_input(INPUT_GET, 'htpunktabsaugungstk') . "',
    '" . filter_input(INPUT_GET, 'htabluftsicherheitsschrankunterbaustk') . "',
    '" . filter_input(INPUT_GET, 'htabluftsicherheitsschrankstk') . "',
    '" . filter_input(INPUT_GET, 'htspuelestk') . "',
    '" . filter_input(INPUT_GET, 'htkühlwasser') . "',
    '" . filter_input(INPUT_GET, 'o2mangel') . "',
    '" . filter_input(INPUT_GET, 'co2melder') . "',
    '" . filter_input(INPUT_GET, 'etrj45ports') . "',
    '" . filter_input(INPUT_GET, 'et64a3phasigeinzelanschluss') . "',
    '" . filter_input(INPUT_GET, 'et32a3phasigeinzelanschluss') . "',
    '" . filter_input(INPUT_GET, 'et16a3phasigeinzelanschluss') . "',
    '" . filter_input(INPUT_GET, 'etdigestoriummsr230vsvstk') . "',
    '" . filter_input(INPUT_GET, 'et5x10mm2digestoriumstk') . "',
    '" . filter_input(INPUT_GET, 'et5x10mm2usvstk') . "',
    '" . filter_input(INPUT_GET, 'et5x10mm2svstk') . "',
    '" . filter_input(INPUT_GET, 'et5x10mm2avstk') . "',
    '" . filter_input(INPUT_GET, 'wasserqual3lmin') . "',
    '" . filter_input(INPUT_GET, 'wasserqual2ltag') . "',
    '" . filter_input(INPUT_GET, 'wasserqual1ltag') . "',
    '" . filter_input(INPUT_GET, 'wasserqual3') . "',
    '" . filter_input(INPUT_GET, 'wasserqual2') . "',
    '" . filter_input(INPUT_GET, 'wasserqual1') . "',
    '" . filter_input(INPUT_GET, 'lhe') . "',
    '" . filter_input(INPUT_GET, 'lnltag') . "',
    '" . filter_input(INPUT_GET, 'ln') . "',
    '" . filter_input(INPUT_GET, 'n2reinheit') . "',
    '" . filter_input(INPUT_GET, 'n2lmin') . "',
    '" . filter_input(INPUT_GET, 'arreinheit') . "',
    '" . filter_input(INPUT_GET, 'arlmin') . "',
    '" . filter_input(INPUT_GET, 'hereinheit') . "',
    '" . filter_input(INPUT_GET, 'helmin') . "',
    '" . filter_input(INPUT_GET, 'h2reinheit') . "',
    '" . filter_input(INPUT_GET, 'h2lmin') . "',
    '" . filter_input(INPUT_GET, 'dliso8573') . "',
    '" . filter_input(INPUT_GET, 'dllmin') . "',
    '" . filter_input(INPUT_GET, 'valmin') . "',
    '" . filter_input(INPUT_GET, 'co2lmin') . "',
    '" . filter_input(INPUT_GET, 'co2reinheit') . "',
    '" . filter_input(INPUT_GET, 'o2lmin') . "',
    '" . filter_input(INPUT_GET, 'o2reinheit') . "',
    '" . filter_input(INPUT_GET, 'laserklasse') . "',
    '" . filter_input(INPUT_GET, 'AnschlLeistung_AV') . "',
    '" . filter_input(INPUT_GET, 'AnschlLeistung_SV') . "',
    '" . filter_input(INPUT_GET, 'AnschlLeistung_ZSV') . "',
    '" . filter_input(INPUT_GET, 'AnschlLeistung_USV') . "',
    '" . filter_input(INPUT_GET, 'SSDs_AV') . "',
    '" . filter_input(INPUT_GET, 'SSDs_SV') . "',
    '" . filter_input(INPUT_GET, 'SSDs_ZSV') . "',
    '" . filter_input(INPUT_GET, 'SSDs_USV') . "',
    '" . filter_input(INPUT_GET, 'CEE16A Stk') . "')";


if ($mysqli->query($sql) === TRUE) {
    echo "Raum erfolgreich hinzugefügt!";
} else {
    echo "Error: " . $sql . "<br>" . $mysqli->error;
}

$mysqli->close();

?>
