<?php

$unitSets = [
    'length' => ["", "mm", "cm", "m"],
    'weight' => ["", "μg", "mg", "g", "dg", "kg", "t"],
    'time' => ["", "s", "min", "h"],
    'frequency' => ["", "Hz", "kHz", "MHz", "GHz"],
    'temp' => ["", "K", "°C"],
    'volume' => ["", "ml", "l", "m³"],
    'connection' => ["", "DN", "Zoll", '"'],
    'angle' => ["", "°"],
    'voltage' => ["", "V", "kV"],
    'current' => ["", "mA", "A", "kA"],
    'resistance' => ["", "mΩ", "Ω", "kΩ"],
    'power' => ["", "W", "kW", "VA", "kVA"],
    'force' => ["", "N", "kN"],
    'torque' => ["", "Nm", "kNm"],
    'pressure' => ["", "kg/cm²", "N/m²", "kg/m²"],
    'flow' => ["", "l/min", "m³/h"],
    'volumetricFlow' => ["", "ml/h", "l/h", "m³/h", "%"],
    'noise' => ["", "dB(A)"],
    'wallReinforcement' => ["", "kg/lfm"],
    'pieces' => ["", "Stk", "Ja"],
    'piecesPerLength' => ["", "Stk", "Stk/lfm"],
    'piecesOrvolumetricFlow' => ["", "Stk", "l/min"],
    'ratio' => ["", "Verhältnis"],
    'netzartUnit' => ["", "/Akku"],
    'waterHardness' => ["", "°dH", "mmol/l"],
    'explosionZone' => ["", "0", "1", "2", "Keine"],
    'pressureBarMbar' => ["", "bar", "mbar"],
    'massFlowKgH' => ["", "kg/h"],
    'percent' => ["", "%"],
    'wavelength' => ["", "nm", "μm"],
    'money' => ["", "€"],
    'monitorResolution' => ["px", "dpi", ""],
    'monitorDiagonal' => ["cm", "inch", ""],
    'monitorAspectRatio' => ["4:3", "16:9", ""],
    'illumination' => ["", "cd/m²", "lx", "lx/m²"],
];

$valueSets = [
    'boolean' => ["", "Ja", "Nein"],
    'jaOnly' => ["", "Ja"],
    'isoClass' => ["ISO-Klasse", ""],
    'laserClass' => ["1", "1M", "2", "2M", "3R", "3B", "4", ""],
    'wallReinforcementValues' => ["", "50", "100", "150", "200", "Ja"],
    'netzart' => ["", "AV", "SV", "ZSV", "USV", "AV/SV", "SV/ZSV", "ZSV/USV", "Akku"],
    'netzwerk' => [
        "",
        "Ja",
        "Nein",
        "optional",
        "USB",
        "RJ45",
        "USB/RJ45",
        "WLAN",
        "Bluetooth",
        "USB/WLAN",
        "RJ45/WLAN",
        "USB/Bluetooth",
        "RJ45/Bluetooth",
        "USB/RJ45/WLAN",
        "USB/RJ45/Bluetooth",
        "WLAN/Bluetooth",
        "USB/WLAN/Bluetooth",
        "RJ45/WLAN/Bluetooth",
        "USB/RJ45/WLAN/Bluetooth",
    ],
];

function rangeValues($min, $max, $includeEmpty = true): array
{
    $arr = range($min, $max);
    if ($includeEmpty) array_unshift($arr, "");
    return array_map('strval', $arr);
}

$parameterFieldConfig = [
    'Geometrie|Länge|Einheit' => $unitSets['length'],
    'Geometrie|Breite|Einheit' => $unitSets['length'],
    'Geometrie|Höhe|Einheit' => $unitSets['length'],
    'Geometrie|Tiefe|Einheit' => $unitSets['length'],
    'Geometrie|(Eigen-)Gewicht|Einheit' => $unitSets['weight'],
    'Geometrie|Kammerbreite|Einheit' => $unitSets['length'],
    'Geometrie|Kammerhöhe|Einheit' => $unitSets['length'],
    'Geometrie|Kammertiefe|Einheit' => $unitSets['length'],
    'Geometrie|Biegemoment|Einheit' => $unitSets['torque'],
    'Geometrie|Armlänge 1|Einheit' => $unitSets['length'],
    'Geometrie|Armlänge 2|Einheit' => $unitSets['length'],
    'Elektro|Stromstärke|Einheit' => $unitSets['current'],
    'Elektro|Spannung|Einheit' => $unitSets['voltage'],
    'Elektro|Nennleistung|Einheit' => $unitSets['power'],
    'Elektro|PA|Einheit' => $unitSets['pieces'],
    'Elektro|USV|Wert' => $valueSets['boolean'],
    'Elektro|Netzwerk|Einheit ' => $valueSets['netzwerk'],
    'Elektro|RJ45 Ports|Wert' => rangeValues(0, 30),
    'Elektro|RJ45 Ports|Einheit' => $unitSets['pieces'],
    'Elektro|Steckdosen MVE-DVE AV|Wert' => rangeValues(0, 30),
    'Elektro|Steckdosen MVE-DVE SV|Wert' => rangeValues(0, 30),
    'Elektro|Steckdosen MVE-DVE ZSV|Wert' => rangeValues(0, 30),
    'Elektro|Steckdosen_MVE_DVE_Roentgen|Wert' => rangeValues(0, 5),
    'Elektro|Steckdosen_MVE_DVE_Laser|Wert' => rangeValues(0, 5),
    'Elektro|Steckdosen MVE-DVE AV|Einheit' => $unitSets['piecesPerLength'],
    'Elektro|Steckdosen MVE-DVE SV|Einheit' => $unitSets['piecesPerLength'],
    'Elektro|Steckdosen MVE-DVE ZSV|Einheit' => $unitSets['piecesPerLength'],
    'Elektro|Steckdosen_MVE_DVE_Roentgen|Einheit' => $unitSets['piecesPerLength'],
    'Elektro|Steckdosen_MVE_DVE_Laser|Einheit' => $unitSets['piecesPerLength'],
    'Elektro|Innenwiderstand_Zuleitung|Einheit' => $unitSets['resistance'],
    'Elektro|Netzart|Wert' => $valueSets['netzart'],
    'Elektro|Netzart|Einheit' => $unitSets['netzartUnit'],
    'Elektro|Frequenzbereich|Einheit' => $unitSets['frequency'],
    'Elektro|IT-Anbindung erforderlich|Wert' => $valueSets['boolean'],
    'Elektro|Reinraummonitoring|Einheit' => $valueSets['boolean'],
    'Elektro|Direktanschluss|Einheit' => $valueSets['boolean'],
    'Elektro|Video-Routing|Wert' => $valueSets['boolean'],
    'Elektro|Kreise AV|Wert' => rangeValues(0, 2),
    'Elektro|Kreise SV|Wert' => rangeValues(0, 2),
    'Elektro|Kreise ZSV|Wert' => rangeValues(0, 2),
    'HKLS|Abwärme|Einheit' => $unitSets['power'],
    'HKLS|Warmwasser_Strom|Einheit' => $unitSets['flow'],
    'HKLS|Kaltwasser_Strom|Einheit' => $unitSets['flow'],
    'HKLS|Voll_entsalztes Wasser_Strom|Einheit' => $unitSets['flow'],
    'HKLS|Abluftstrom|Einheit' => $unitSets['volumetricFlow'],
    'HKLS|Abflussstrom|Einheit' => $unitSets['flow'],
    'HKLS|Abflussdurchmesser|Einheit' => $unitSets['connection'],
    'HKLS|Ablufttemperatur|Einheit' => $unitSets['temp'],
    'HKLS|Kaltwasser_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Warmwasser_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Abluftdurchmesser|Einheit' => $unitSets['connection'],
    'HKLS|Zuluftstrom|Einheit' => $unitSets['volumetricFlow'],
    'HKLS|Fortluftstrom|Einheit' => $unitSets['volumetricFlow'],
    'HKLS|Druckluftanschluss|Einheit' => $unitSets['connection'],
    'HKLS|Druckluft_Strom|Einheit' => $unitSets['flow'],
    'HKLS|Druckluft_Druck|Einheit' => $unitSets['pressureBarMbar'],
    'HKLS|Druckluftqualität|Wert' => $valueSets['isoClass'],
    'HKLS|WFI_Strom|Einheit' => $unitSets['flow'],
    'HKLS|Voll_entsalztes Wasser_Temp_Max|Einheit' => $unitSets['temp'],
    'HKLS|Warmwasser_Temp_Max|Einheit' => $unitSets['temp'],
    'HKLS|Kaltwasser_Temp_ Max|Einheit' => $unitSets['temp'],
    'HKLS|Kühlwasser_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Kühlwasser_Strom|Einheit' => $unitSets['flow'],
    'HKLS|Sterilisierdampf_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Sterilisierdampf_Strom|Einheit' => $unitSets['massFlowKgH'],
    'HKLS|Abdampf_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Abdampf_Strom|Einheit' => $unitSets['massFlowKgH'],
    'HKLS|WFI_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Schwarzdampf_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Schwarzdampf_Strom|Einheit' => $unitSets['massFlowKgH'],
    'HKLS|Voll_entsalztes Wasser_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Voll_entsalztes Wasser_Verbrauch|Einheit' => $unitSets['volumetricFlow'],
    'HKLS|Zuluftdurchmesser|Einheit' => $unitSets['length'],
    'HKLS|PW_Strom|Einheit' => $unitSets['flow'],
    'HKLS|PW_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Abflusstemperatur|Einheit' => $unitSets['temp'],
    'HKLS|WFI_Temperatur|Einheit' => $unitSets['temp'],
    'HKLS|PW_Temperatur|Einheit' => $unitSets['temp'],
    'HKLS|Abluftventilator|Wert' => $valueSets['boolean'],
    'HKLS|Kühlwasser_Abwärme|Einheit' => $unitSets['power'],
    'HKLS|Abfluss_Boden|Einheit' => $unitSets['connection'],
    'HKLS|Kondensat_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Kühlwasser_Temperatur|Einheit' => $unitSets['temp'],
    'HKLS|Kühlwasser_Vorlauf_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Kühlwasser_Rücklauf_Anschluss|Einheit' => $unitSets['connection'],
    'HKLS|Trennung EN1717|Wert' => $valueSets['boolean'],
    'HKLS|Temperaturbereich Primärseite|Einheit' => $unitSets['temp'],
    'HKLS|Temperaturbereich Sekundärseite|Einheit' => $unitSets['temp'],
    'HKLS|Warmwasser_Temp_Min|Einheit' => $unitSets['temp'],
    'HKLS|Kaltwasser_Wasserhaerte|Einheit' => $unitSets['waterHardness'],
    'HKLS|Warmwasser_Wasserhaerte|Einheit' => $unitSets['waterHardness'],
    'Ergonomie|Lärm|Einheit' => $unitSets['noise'],
    'Allgemein|Volumen|Einheit' => $unitSets['volume'],
    'Allgemein|Kosten_unbestätigt|Einheit' => $unitSets['money'],
    'Allgemein|Vergabe abgeschlossen|Wert' => $valueSets['boolean'],
    'Infusionstechnik|Fördergenauigkeit|Einheit' => $unitSets['volumetricFlow'],
    'Infusionstechnik|Akkulaufzeit_20ml/h|Einheit' => $unitSets['time'],
    'Infusionstechnik|Förderratenauflösung|Einheit' => $unitSets['volumetricFlow'],
    'Infusionstechnik|Geräuschpegel_999 ml/h|Einheit' => $unitSets['noise'],
    'Kühlschrank/Klimaschrank|Temperaturbereich|Einheit' => $unitSets['temp'],
    'Kühlschrank/Klimaschrank|rel. Feuchtigkeitsbereich|Einheit' => $unitSets ['percent'],
    'Labor|Anschluss_Medienzelle|Einheit' => $unitSets['connection'],
    'Endoskope|Außendurchmesser_Schlauch|Einheit' => $unitSets['length'],
    'Endoskope|Durchmesser_Instrumentierkanal|Einheit' => $unitSets['length'],
    'Endoskope|Arbeitslänge|Einheit' => $unitSets['length'],
    'Endoskope|Gesamtlänge|Einheit' => $unitSets['length'],
    'Endoskope|Blickwinkel_Sichtfeld|Einheit' => $unitSets['angle'],
    'Endoskope|Fokusbereich_Schärfentiefe|Einheit' => $unitSets['length'],
    'Endoskope|Winkelung_Auf_Ab|Einheit' => $unitSets['angle'],
    'Endoskope|Winkelung_Rechts_Links|Einheit' => $unitSets['angle'],
    'Monitor|Auflösung|Einheit' => $unitSets['monitorResolution'],
    'Monitor|Monitordiagonale|Einheit' => $unitSets['monitorDiagonal'],
    'Monitor|Seitenverhältnis|Einheit' => $unitSets['monitorAspectRatio'],
    'Monitor|Blickwinkel|Einheit' => $unitSets['angle'],
    'Monitor|Kontrast|Einheit' => $unitSets['ratio'],
    'Monitor|Helligkeit|Einheit' => $unitSets['illumination'],
    'Laser|Wellenlänge|Einheit' => $unitSets['wavelength'],
    'Laser|Laserleistung|Einheit' => $unitSets['power'],
    'Laser|Laserklasse|Wert' => $valueSets['laserClass'],
    'MedGas|Stickstoff_Strom|Einheit' => $unitSets['flow'],
    'MedGas|Argon_Strom|Einheit' => $unitSets['flow'],
    'MedGas|O2 Anschluss|Wert' => rangeValues(0, 40),
    'MedGas|DL-5 Anschluss|Wert' => rangeValues(0, 9),
    'MedGas|VAC Anschluss|Wert' => $valueSets['boolean'],
    'MedGas|DL-10 Anschluss|Wert' => rangeValues(0, 9),
    'MedGas|DL-10 Anschluss|Einheit' => $unitSets['pieces'],
    'MedGas|N2 Anschluss|Wert' => rangeValues(0, 40),
    'MedGas|N2 Anschluss|Einheit' => $unitSets ['piecesOrvolumetricFlow'],
    'MedGas|NGA Anschluss|Wert' => rangeValues(0, 40),
    'MedGas|N2O Anschluss|Wert' => rangeValues(0, 40),
    'MedGas|CO2 Anschluss|Wert' => rangeValues(0, 40),
    'Beleuchtung|Beleuchtungsstärke|Einheit' => $unitSets['illumination'],
    'Statik|Punktlast|Einheit' => $unitSets['force'],
    'Statik|Wandverstärkung|Wert' => $valueSets['wallReinforcementValues'],
    'Statik|Wandverstärkung|Einheit' => $unitSets['wallReinforcement'],
    'US-Sonden|Frequenzbereich|Einheit' => $unitSets['frequency'],
    'Waage|Mindesteinwaage|Einheit' => $unitSets['weight'],
    'Waage|Maximaleinwaage|Einheit' => $unitSets['weight'],
    'Waage|Ablesbarkeit|Einheit' => $unitSets['weight'],
    'MSR|GLT|Einheit' => $valueSets['jaOnly'],
    'Geometrie_Einbringung|Einbringweg_Breite|Einheit' => $unitSets['length'],
    'Geometrie_Einbringung|Einbringweg_Höhe|Einheit' => $unitSets['length'],
    'Geometrie_Einbringung|Einbringweg_Tiefe|Einheit' => $unitSets['length'],
    'Geometrie_Einbringung|Einbringweg_Gewicht|Einheit' => $unitSets['weight'],
    'Geometrie_Einbringung|Einbringweg_Flächenlast|Einheit' => $unitSets['pressure'],
    'Geometrie_Einbringung|Einbringweg_Breite_2|Einheit' => $unitSets['length'],
    'Geometrie_Einbringung|Einbringweg_Höhe_2|Einheit' => $unitSets['length'],
    'Geometrie_Einbringung|Einbringweg_Tiefe_2|Einheit' => $unitSets['length'],
];
