<?php
// 25 FX
require_once "utils/_utils.php";
check_login();
$mysqli = utils_connect_sql();

$sql = "SELECT r.tabelle_projekte_idTABELLE_Projekte, 
r.idTABELLE_Räume, 
r.TABELLE_Funktionsteilstellen_idTABELLE_Funktionsteilstellen, 
f.Nummer, 
f.Bezeichnung,
r.`MT-relevant`, 
r.Raumnr, 
r.Raumbezeichnung, 
r.`Funktionelle Raum Nr`, 
r.Raumnummer_Nutzer, 
r.`Raumbereich Nutzer`, 
r.Geschoss, 
r.Bauetappe, 
r.Bauabschnitt, 
r.Nutzfläche, 
CASE 
    WHEN r.Abdunkelbarkeit = 0 THEN 'kein Anspruch'
    WHEN r.Abdunkelbarkeit = 1 THEN 'vollverdunkelbar'
    WHEN r.Abdunkelbarkeit = 2 THEN 'abdunkelbar '
    ELSE '-' 
  END AS Abdunkelbarkeit,
r.Strahlenanwendung, 
r.Laseranwendung, 
r.H6020, 
r.GMP, 
r.ISO, 
r.AR_Statik_relevant, 
r.AR_AP_permanent, 
r.`1 Kreis O2`, 
r.`2 Kreis O2`, 
r.`1 Kreis Va`, 
r.`2 Kreis Va`, 
r.VA, 
r.`1 Kreis DL-5`, 
r.`2 Kreis DL-5`, 
r.`DL-5`,  
r.`DL-10`, 
r.`DL-tech`,
r.`He-RF`, 
r.NGA, 
r.N2O, 
r.AV, 
r.SV, 
r.ZSV, 
r.USV, 
r.`IT Anbindung`, 
r.Anwendungsgruppe, 
r.`Allgemeine Hygieneklasse`, 
r.Raumhoehe, 
r.`Raumhoehe 2`, 
r.Belichtungsfläche, 
r.Umfang, 
r.Volumen, 
r.ET_Anschlussleistung_W, 
r.ET_Anschlussleistung_AV_W,
r.ET_Anschlussleistung_SV_W,
r.ET_Anschlussleistung_ZSV_W,
r.ET_Anschlussleistung_USV_W,
r.`EL_AV Steckdosen Stk`,
r.`EL_SV Steckdosen Stk`,
r.`EL_ZSV Steckdosen Stk`, 
r.`EL_USV Steckdosen Stk`,
r.`EL_Roentgen 16A CEE Stk`,
r.`EL_Laser 16A CEE Stk`, 
r.`ET_RJ45-Ports`, 
r.HT_Waermeabgabe_W, 
r.VEXAT_Zone, 
r.HT_Abluft_Vakuumpumpe, 
r.HT_Abluft_Schweissabsaugung_Stk, 
r.HT_Abluft_Esse_Stk, 
r.HT_Abluft_Rauchgasabzug_Stk, 
r.HT_Abluft_Digestorium_Stk, 
r.HT_Punktabsaugung_Stk, 
r.HT_Abluft_Sicherheitsschrank_Unterbau_Stk,
r.HT_Abluft_Sicherheitsschrank_Stk, 
r.HT_Spuele_Stk, 
r.HT_Kühlwasser, 
r.`ET_RJ45-Ports`, 
r.ET_64A_3Phasig_Einzelanschluss, 
r.ET_32A_3Phasig_Einzelanschluss, 
r.ET_16A_3Phasig_Einzelanschluss, 
r.ET_Digestorium_MSR_230V_SV_Stk, 
r.ET_5x10mm2_Digestorium_Stk, 
r.ET_5x10mm2_USV_Stk, 
r.ET_5x10mm2_SV_Stk, 
r.ET_5x10mm2_AV_Stk, 
r.`Wasser Qual 3 l/min`, 
r.`Wasser Qual 2 l/Tag`, 
r.`Wasser Qual 1 l/Tag`, 
r.`Wasser Qual 3`, 
r.`Wasser Qual 2`, 
r.`Wasser Qual 1`, 
r.LHe, 
r.`LN l/Tag`,
r.LN, 
r.`N2 Reinheit`, 
r.`N2 l/min`, 
r.`Ar Reinheit`,
r.`Ar l/min`, 
r.`He Reinheit`,
r.`He l/min`, 
r.`H2 Reinheit`,
r.`H2 l/min`, 
r.`DL ISO 8573`, 
r.`DL l/min`, 
r.`VA l/min`,
r.`CO2 l/min`,
r.`CO2 Reinheit`,
r.`O2 l/min`,
r.`O2 Reinheit`,
r.Laserklasse,
r.HT_Waermeabgabe_W,
r.`Fussboden OENORM B5220`,
r.HT_Notdusche,
r.VE_Wasser,
r.Ar,
r.H2,
r.He,
r.Kr,
r.N2,
r.Ne,
r.NH3,
r.O2,
r.CO2,
r.C2H2,
r.Propan_Butan,
r.N2H2,
r.Inertgas,
r.`Ar_CO2_Mix`,
r.ArCal15,
r.`O2_Mangel`,
r.`CO2_Melder`,
r.`NH3_Sensor`,
r.`H2_Sensor`,
r.Blitzleuchte,
r.`O2_Sensor`,
r.`Acetylen_Melder`,
r.`HT_Luftwechsel 1/h`,
r.EL_Not_Aus_Funktion,
r.EL_Not_Aus,
r.EL_Signaleinrichtung,
r.`HT_Raumtemp Sommer °C`,
r.`HT_Raumtemp Winter °C`,
r.ET_PA_Stk,
r.HT_Kaltwasser,
r.HT_Warmwasser,
r.HT_Abwasser_Stk,
r.AR_Empf_Breite_cm,
r.AR_Empf_Tiefe_cm,
r.AR_Empf_Hoehe_cm,
r.AR_Flaechenlast_kgcm2,
r.HT_Tempgradient_Ch,
r.HT_Abluft_Geraete,
r.`ET_EMV_ja-nein`,
r.`Entfallen`, 
r.AR_Statik_relevant,
r.`Fussboden`,
r.`Decke`,
r.`Anmerkung AR`,
r.`Taetigkeiten`,
r.`AR_APs`,
r.`AP_Gefaehrdung`,
r.`AP_Geistige`,
r.`Belichtungsfläche`,
r.`ET_EMV`,
r.`Spezialgase`,
r.`Gaswarneinrichtung-Art`,
r.`AR_Schwingungsklasse`,
r.`EL_Beleuchtungsstaerke`,
r.`HT_Luftmenge m3/h`,
r.`HT_Kuehlung`,          
r.`HT_Kaelteabgabe_Typ`,  
r.`HT_Heizung`,           
r.`HT_Waermeabgabe_Typ`,  
r.`HT_Belueftung`,        
r.`HT_Entlueftung`,       
r.`PHY_Akustik_Schallgrad`,
r.`EL_Laser 32A Stk`,
    (
        SELECT COUNT(*)
        FROM tabelle_räume_has_tabelle_elemente re
        WHERE re.TABELLE_Räume_idTABELLE_Räume = r.idTABELLE_Räume
    ) AS element_mask
FROM tabelle_räume r
INNER JOIN tabelle_funktionsteilstellen f 
    ON r.TABELLE_Funktionsteilstellen_idTABELLE_Funktionsteilstellen = f.idTABELLE_Funktionsteilstellen
WHERE r.tabelle_projekte_idTABELLE_Projekte = ?
ORDER BY r.Raumnr, r.`Raumbereich Nutzer`";

$stmt = $mysqli->prepare($sql);
$stmt->bind_param("i", $_SESSION['projectID']);
$result = $stmt->execute();
$result = $stmt->get_result();
$mysqli->close();
$data = array();
while ($row = $result->fetch_assoc()) {
    $data[] = $row;
}

header('Content-Type: application/json');
echo json_encode($data);

