window.onload = function () {
    $.get("navbar.html", function (data) {
        $("#limet-navbar").html(data);
        $('.navbar-nav').find('li:nth-child(3)').addClass('active');
    }); 
};

const buttonRanges = [
    {name: 'RAUM', start: 7, end: 23},
    {name: 'HKLS', start: 24, end: 29},
    {name: 'ELEK', start: 30, end: 37},
    {name: 'MEDGAS', start: 38, end: 51},
    {name: 'LAB', start: 52, end: 100},
    {name: 'LAB-GAS', start: 54, end: 79},
    {name: 'LAB-ET', start: 80, end: 87},
    {name: 'LAB-HT', start: 88, end: 95}, 
    {name: 'LAB-H2O', start: 95, end: 100}
];
 
const fieldDeclaration = [ 
//    {label: 'Projek ID', name: 'tabelle_projekte_idTABELLE_Projekte'},
    {label: 'Raum ID', name: 'idTABELLE_Räume'},
//    {label: 'Funktionsstellen ID', name: 'TABELLE_Funktionsteilstellen_idTABELLE_Funktionsteilstellen'},
//    {label: 'MT-rel.', name: 'MT-relevant', type: 'radio',
//            options: [
//                { label: 'Nein', value: 0 },
//                { label: 'Ja', value: 1 }
//            ]},
//    {label: 'Raumbez.', name: 'Raumbezeichnung'},
//    {label: 'Raumnr', name: 'Raumnr'},
//    //RAUMDETAILS
//    {label: 'Funkt.R.Nr', name: 'Funktionelle Raum Nr'},
//    {label: 'DIN13080', name: 'DIN13080'},
//    {label: 'Raumnr Nutzer', name: 'Raumnummer_Nutzer'},
//    {label: 'Raumbereich', name: 'Raumbereich Nutzer'},
//    {label: 'Geschoss', name: 'Geschoss'},
//    {label: 'Bauetappe', name: 'Bauetappe'},
//    {label: 'Bauabschnitt', name: 'Bauabschnitt'},
//    {label: 'Nutzfläche', name: 'Nutzfläche'},
//    {label: 'Abdunkelbar', name: 'Abdunkelbarkeit'},
//    {label: 'Strahlenanw.', name: 'Strahlenanwendung'},
//    {label: 'Laseranw.', name: 'Laseranwendung'},
//    {label: 'Allg. Hygieneklasse', name: 'Allgemeine Hygieneklasse'},
//    {label: 'Raumhöhe', name: 'Raumhoehe'},
//    {label: 'Raumhöhe2', name: 'Raumhoehe 2'},
//    {label: 'Belichtungsfläche', name: 'Belichtungsfläche'},
//    {label: 'Umfang', name: 'Umfang'},
//    {label: 'Volumen', name: 'Volumen'},
//    //HKLS
//    {label: 'H6020', name: 'H6020',
//     type: 'select', options: [
//                { label: 'H1a', value: 'H1a' },
//                { label: 'H1b', value: 'H1b' },
//                { label: 'H2a', value: 'H2a' },
//                { label: 'H2b', value: 'H2b' },
//                { label: 'H2c', value: 'H2c' },
//                { label: 'H3', value: 'H3' },
//                { label: 'H4', value: 'H4' }
//            ]},
//    {label: 'GMP', name: 'GMP'},
//    {label: 'ISO', name: 'ISO'},
//    {label: 'Waermeabgabe[W]', name: 'HT_Waermeabgabe_W'},
//    {label: 'Spüle_Stk', name: 'HT_Spuele_Stk'},
//    {label: 'Kühlwasser', name: 'HT_Kühlwasser'},
//    //ELEKTRO
//    {label: 'AWG', name: 'Anwendungsgruppe'},
//    {label: 'AV', name: 'AV'},
//    {label: 'SV', name: 'SV'},
//    {label: 'ZSV', name: 'ZSV'},
//    {label: 'USV', name: 'USV'},
//    {label: 'IT', name: 'IT Anbindung'},
//    {label: 'Anschlussleistung[W]', name: 'ET_Anschlussleistung_W'},
//    {label: 'RJ45-Ports', name: 'ET_RJ45-Ports'},
//    //MEDGASE
//    {label: '1 Kreis O2', name: '1 Kreis O2'},
//    {label: '2 Kreis O2', name: '2 Kreis O2'},
//    {label: 'O2', name: 'O2'},
//    {label: '1 Kreis Va', name: '1 Kreis Va'},
//    {label: '2 Kreis Va', name: '2 Kreis Va'},
//    {label: 'VA', name: 'VA'},
//    {label: '1 Kreis DL-5', name: '1 Kreis DL-5'},
//    {label: '2 Kreis DL-5', name: '2 Kreis DL-5'},
//    {label: 'DL-5', name: 'DL-5'},
//    {label: 'DL-10', name: 'DL-10'},
//    {label: 'DL-tech', name: 'DL-tech'},
//    {label: 'CO2', name: 'CO2'},
//    {label: 'NGA', name: 'NGA'},
//    {label: 'N2O', name: 'N2O'},
//    // LAB
//    {label: 'VEXAT_Zone', name: 'VEXAT_Zone'},
//    {label: 'Laserklasse', name: 'Laserklasse'},
//    // LAB GASE
//    {label: 'H2', name: 'H2'},
//    {label: 'He', name: 'He'},
//    {label: 'He-RF', name: 'He-RF'},
//    {label: 'Ar', name: 'Ar'},
//    {label: 'N2', name: 'N2'},
//    {label: 'O2_Mangel', name: 'O2_Mangel'},
//    {label: 'CO2_Melder', name: 'CO2_Melder'},
//    {label: 'LHe', name: 'LHe'},
//    {label: 'LN l/Tag', name: 'LN l/Tag'},
//    {label: 'LN', name: 'LN'},
//    {label: 'N2 Reinheit', name: 'N2 Reinheit'},
//    {label: 'N2 l/min', name: 'N2 l/min'},
//    {label: 'Ar Reinheit', name: 'Ar Reinheit'},
//    {label: 'Ar l/min', name: 'Ar l/min'},
//    {label: 'He Reinheit', name: 'He Reinheit'},
//    {label: 'He l/min', name: 'He l/min'},
//    {label: 'H2 Reinheit', name: 'H2 Reinheit'},
//    {label: 'H2 l/min', name: 'H2 l/min'},
//    {label: 'DL ISO 8573', name: 'DL ISO 8573'},
//    {label: 'DL l/min', name: 'DL l/min'},
//    {label: 'VA l/min', name: 'VA l/min'},
//    {label: 'CO2 l/min', name: 'CO2 l/min'},
//    {label: 'CO2 Reinheit', name: 'CO2 Reinheit'},
//    {label: 'O2 l/min', name: 'O2 l/min'},
//    {label: 'O2 Reinheit', name: 'O2 Reinheit'},
//    // LAB ET
//    {label: '64A_3Phasig_Einzelanschluss', name: 'ET_64A_3Phasig_Einzelanschluss'},
//    {label: '32A_3Phasig_Einzelanschluss', name: 'ET_32A_3Phasig_Einzelanschluss'},
//    {label: '16A_3Phasig_Einzelanschluss', name: 'ET_16A_3Phasig_Einzelanschluss'},
//    {label: 'Digestorium_MSR_230V_SV_Stk', name: 'ET_Digestorium_MSR_230V_SV_Stk'},
//    {label: '5x10mm2_Digestorium_Stk', name: 'ET_5x10mm2_Digestorium_Stk'},
//    {label: '5x10mm2_USV_Stk', name: 'ET_5x10mm2_USV_Stk'},
//    {label: '5x10mm2_SV_Stk', name: 'ET_5x10mm2_SV_Stk'},
//    {label: '5x10mm2_AV_Stk', name: 'ET_5x10mm2_AV_Stk'},
//    //LAB HT
//    {label: 'Abluft Vakuumpumpe', name: 'HT_Abluft_Vakuumpumpe'},
//    {label: 'Abluft Schweissabsaugung Stk', name: 'HT_Abluft_Schweissabsaugung_Stk'},
//    {label: 'Abluft Esse_Stk', name: 'HT_Abluft_Esse_Stk'},
//    {label: 'Abluft Rauchgasabzug_Stk', name: 'HT_Abluft_Rauchgasabzug_Stk'},
//    {label: 'Abluft Digestorium_Stk', name: 'HT_Abluft_Digestorium_Stk'},
//    {label: 'Punktabsaugung_Stk', name: 'HT_Punktabsaugung_Stk'},
//    {label: 'Abluft Sicherheitsschrank Unterbau Stk', name: 'HT_Abluft_Sicherheitsschrank_Unterbau_Stk'},
//    {label: 'Abluft Sicherheitsschrank Stk', name: 'HT_Abluft_Sicherheitsschrank_Stk'},
//    {label: 'Wasser Qual 3 l/min', name: 'Wasser Qual 3 l/min'},
//    {label: 'Wasser Qual 2 l/Tag', name: 'Wasser Qual 2 l/Tag'},
//    {label: 'Wasser Qual 1 l/Tag', name: 'Wasser Qual 1 l/Tag'},
//    {label: 'Wasser Qual 3', name: 'Wasser Qual 3'},
//    {label: 'Wasser Qual 2', name: 'Wasser Qual 2'},
//    {label: 'Wasser Qual 1', name: 'Wasser Qual 1'}
];

const columnsDefinition = [
//    { data: '', defaultContent: '', title: "Select", render:  $.fn.dataTable.render.select(), searchable: false, orderable: false },
    { data: 'tabelle_projekte_idTABELLE_Projekte', title: 'Projek ID', visible: false, searchable: false },
    { data: 'idTABELLE_Räume', title: 'Raum ID'}, //, visible: false, searchable: false },
    { data: 'TABELLE_Funktionsteilstellen_idTABELLE_Funktionsteilstellen', title: 'Funktionsstellen ID' , visible: false, searchable: false},
    { data: 'MT-relevant', title: 'MT-rel.', name: 'MT-relevant', render: function (data) {return data === '1' ? 'Ja' : 'Nein';}},
    { data: 'Raumbezeichnung', title: 'Raumbez.' },
    { data: 'Raumnr', title: 'Raumnr' },
    { data: 'Funktionelle Raum Nr', title: 'Funkt.R.Nr' },
    { data: '', title: 'DIN13080',  defaultContent: ''},
    { data: 'Raumnummer_Nutzer', title: 'Raumnr Nutzer' },
    { data: 'Raumbereich Nutzer', title: 'Raumbereich' },
    { data: 'Geschoss', title: 'Geschoss' },
    { data: 'Bauetappe', title: 'Bauetappe' },
    { data: 'Bauabschnitt', title: 'Bauabschnitt' },
    { data: 'Nutzfläche', title: 'Nutzfläche' },
    { data: 'Abdunkelbarkeit', title: 'Abdunkelbar' },
    { data: 'Strahlenanwendung', title: 'Strahlenanw.' },
    { data: 'Laseranwendung', title: 'Laseranw.' },
    { data: 'Allgemeine Hygieneklasse', title: 'Allg. Hygieneklasse' },
    { data: 'Raumhoehe', title: 'Raumhoehe' },
    { data: 'Raumhoehe 2', title: 'Raumhoehe2' },
    { data: 'Belichtungsfläche', title: 'Belichtungsfläche' },
    { data: 'Umfang', title: 'Umfang' },
    { data: 'Volumen', title: 'Volumen' },
    { data: 'H6020', title: 'H6020' },
    { data: 'GMP', title: 'GMP' },
    { data: 'ISO', title: 'ISO' },
    { data: 'HT_Waermeabgabe_W', title: 'HT_Waermeabgabe_W' },
    { data: 'HT_Spuele_Stk', title: 'HT_Spuele_Stk' },
    { data: 'HT_Kühlwasser', title: 'HT_Kühlwasser' },
    { data: 'Anwendungsgruppe', title: 'AWG' },
    { data: 'AV', title: 'AV' },
    { data: 'SV', title: 'SV' },
    { data: 'ZSV', title: 'ZSV' },
    { data: 'USV', title: 'USV' },
    { data: 'IT Anbindung', title: 'IT',render: function (data) {return data === '1' ? 'Ja' : 'Nein';}},
    { data: 'ET_Anschlussleistung_W', title: 'ET_Anschlussleistung_W' },
    { data: 'ET_RJ45-Ports', title: 'ET_RJ45-Ports' },
    { data: '1 Kreis O2', title: '1 Kreis O2' },
    { data: '2 Kreis O2', title: '2 Kreis O2' },
    { data: 'O2', title: 'O2' },
    { data: '1 Kreis Va', title: '1 Kreis Va' },
    { data: '2 Kreis Va', title: '2 Kreis Va' },
    { data: 'VA', title: 'VA' },
    { data: '1 Kreis DL-5', title: '1 Kreis DL-5' },
    { data: '2 Kreis DL-5', title: '2 Kreis DL-5' },
    { data: 'DL-5', title: 'DL-5' },
    { data: 'DL-10', title: 'DL-10' },
    { data: 'DL-tech', title: 'DL-tech' },
    { data: 'CO2', title: 'CO2' },
    { data: 'NGA', title: 'NGA' },
    { data: 'N2O', title: 'N2O' },
    { data: 'VEXAT_Zone', title: 'VEXAT_Zone' },
    { data: 'Laserklasse', title: 'Laserklasse' },
    { data: 'H2', title: 'H2' },
    { data: 'He', title: 'He' },
    { data: 'He-RF', title: 'He-RF' },
    { data: 'Ar', title: 'Ar' },
    { data: 'N2', title: 'N2' },
    { data: 'O2_Mangel', title: 'O2_Mangel' },
    { data: 'CO2_Melder', title: 'CO2_Melder' },
    { data: 'LHe', title: 'LHe' },
    { data: 'LN l/Tag', title: 'LN l/Tag' },
    { data: 'LN', title: 'LN' },
    { data: 'N2 Reinheit', title: 'N2 Reinheit' },
    { data: 'N2 l/min', title: 'N2 l/min' },
    { data: 'Ar Reinheit', title: 'Ar Reinheit' },
    { data: 'Ar l/min', title: 'Ar l/min' },
    { data: 'He Reinheit', title: 'He Reinheit' },
    { data: 'He l/min', title: 'He l/min' },
    { data: 'H2 Reinheit', title: 'H2 Reinheit' },
    { data: 'H2 l/min', title: 'H2 l/min' },
    { data: 'DL ISO 8573', title: 'DL ISO 8573' },
    { data: 'DL l/min', title: 'DL l/min' },
    { data: 'VA l/min', title: 'VA l/min' },
    { data: 'CO2 l/min', title: 'CO2 l/min' },
    { data: 'CO2 Reinheit', title: 'CO2 Reinheit' },
    { data: 'O2 l/min', title: 'O2 l/min' },
    { data: 'O2 Reinheit', title: 'O2 Reinheit' },
    { data: 'ET_64A_3Phasig_Einzelanschluss', title: '64A_3Phasig_Einzelanschluss' },
    { data: 'ET_32A_3Phasig_Einzelanschluss', title: '32A_3Phasig_Einzelanschluss' },
    { data: 'ET_16A_3Phasig_Einzelanschluss', title: '16A_3Phasig_Einzelanschluss' },
    { data: 'ET_Digestorium_MSR_230V_SV_Stk', title: 'Digestorium_MSR_230V_SV_Stk' },
    { data: 'ET_5x10mm2_Digestorium_Stk', title: '5x10mm2_Digestorium_Stk' },
    { data: 'ET_5x10mm2_USV_Stk', title: '5x10mm2_USV_Stk' },
    { data: 'ET_5x10mm2_SV_Stk', title: '5x10mm2_SV_Stk' },
    { data: 'ET_5x10mm2_AV_Stk', title: '5x10mm2_AV_Stk' },
    { data: 'HT_Abluft_Vakuumpumpe', title: 'HT_Abluft_Vakuumpumpe' },
    { data: 'HT_Abluft_Schweissabsaugung_Stk', title: 'HT_Abluft_Schweissabsaugung_Stk' },
    { data: 'HT_Abluft_Esse_Stk', title: 'HT_Abluft_Esse_Stk' },
    { data: 'HT_Abluft_Rauchgasabzug_Stk', title: 'HT_Abluft_Rauchgasabzug_Stk' },
    { data: 'HT_Abluft_Digestorium_Stk', title: 'HT_Abluft_Digestorium_Stk' },
    { data: 'HT_Punktabsaugung_Stk', title: 'HT_Punktabsaugung_Stk' },
    { data: 'HT_Abluft_Sicherheitsschrank_Unterbau_Stk', title: 'HT_Abluft_Sicherheitsschrank_Unterbau_Stk' },
    { data: 'HT_Abluft_Sicherheitsschrank_Stk', title: 'HT_Abluft_Sicherheitsschrank_Stk' },
    { data: 'Wasser Qual 3 l/min', title: 'Wasser Qual 3 l/min' },
    { data: 'Wasser Qual 2 l/Tag', title: 'Wasser Qual 2 l/Tag' },
    { data: 'Wasser Qual 1 l/Tag', title: 'Wasser Qual 1 l/Tag' },
    { data: 'Wasser Qual 3', title: 'Wasser Qual 3' },
    { data: 'Wasser Qual 2', title: 'Wasser Qual 2' },
    { data: 'Wasser Qual 1', title: 'Wasser Qual 1' }
];