`Raumnr`,
`Raumbezeichnung`,
TABELLE_Funktionsteilstellen_idTABELLE_Funktionsteilstellen, 
`MT-relevant`, 
Raumnr, 
Raumbezeichnung, 
`Funktionelle Raum Nr`, 
Raumnummer_Nutzer, 
`Raumbereich Nutzer`, 
Geschoss, 
Bauetappe, 
Bauabschnitt, 

Nutzfläche, 
Abdunkelbarkeit, 

Strahlenanwendung, 
Laseranwendung, 
H6020, 

GMP, 
ISO, 
`1 Kreis O2`, 
`2 Kreis O2`, 
O2, 
`1 Kreis Va`, 
`2 Kreis Va`, 
VA, 
`1 Kreis DL-5`, 
`2 Kreis DL-5`, 
`DL-5`, 
`DL-10`, 
`DL-tech`,
CO2, 
H2, 
He, 
`He-RF`, 
Ar, 
N2, 
NGA, 
N2O, 
AV, 
SV, 
ZSV, 
USV, 
`IT Anbindung`, 
Anwendungsgruppe, 
`Allgemeine Hygieneklasse`, 
Raumhoehe, 

`Raumhoehe 2`, 
Belichtungsfläche, 
Umfang, 
Volumen, 
ET_Anschlussleistung_W, 
HT_Waermeabgabe_W, 
VEXAT_Zone, 
HT_Abluft_Vakuumpumpe, 
HT_Abluft_Schweissabsaugung_Stk, 
HT_Abluft_Esse_Stk, 
HT_Abluft_Rauchgasabzug_Stk, 
HT_Abluft_Digestorium_Stk, 
HT_Punktabsaugung_Stk, 
HT_Abluft_Sicherheitsschrank_Unterbau_Stk,
HT_Abluft_Sicherheitsschrank_Stk, 
HT_Spuele_Stk, 
HT_Kühlwasser,  O2_Mangel, 
CO2_Melder,  `ET_RJ45-Ports`, 
ET_64A_3Phasig_Einzelanschluss, 
ET_32A_3Phasig_Einzelanschluss, 
ET_16A_3Phasig_Einzelanschluss, 
ET_Digestorium_MSR_230V_SV_Stk, 
ET_5x10mm2_Digestorium_Stk, 
ET_5x10mm2_USV_Stk, 
ET_5x10mm2_SV_Stk, 
ET_5x10mm2_AV_Stk, 
`Wasser Qual 3 l/min`, 
`Wasser Qual 2 l/Tag`, 
`Wasser Qual 1 l/Tag`, 
`Wasser Qual 3`, 
`Wasser Qual 2`, 
`Wasser Qual 1`, 
LHe, 
`LN l/Tag`,
LN, 
`N2 Reinheit`, 
`N2 l/min`, 
`Ar Reinheit`,
`Ar l/min`, 
`He Reinheit`,
`He l/min`, 
`H2 Reinheit`,
`H2 l/min`, 
`DL ISO 8573`, 
`DL l/min`, 
`VA l/min`,
`CO2 l/min`, 
`CO2 Reinheit`, 
`O2 l/min`, 
`O2 l/min`,
`O2 Reinheit`, 
Laserklasse




        save_new_room_all(
                                                                                selectedRowData["TABELLE_Funktionsteilstellen_idTABELLE_Funktionsteilstellen"],
                                                                                selectedRowData["MT-relevant"],
                                                                                selectedRowData["Raumnr"],
                                                                                selectedRowData["Raumbezeichnung"],
                                                                                selectedRowData["Funktionelle Raum Nr"],
                                                                                selectedRowData["Raumnummer_Nutzer"],
                                                                                selectedRowData["Raumbereich Nutzer"],
                                                                                selectedRowData["Geschoss"],
                                                                                selectedRowData["Bauetappe"],
                                                                                selectedRowData["Bauabschnitt"],
                                                                                selectedRowData["Nutzfläche"],
                                                                                selectedRowData["Abdunkelbarkeit"],
                                                                                selectedRowData["Strahlenanwendung"],
                                                                                selectedRowData["Laseranwendung"],
                                                                                selectedRowData["H6020"],
                                                                                selectedRowData["GMP"],
                                                                                selectedRowData["ISO"],
                                                                                selectedRowData["1 Kreis O2"],
                                                                                selectedRowData["2 Kreis O2"],
                                                                                selectedRowData["O2"],
                                                                                selectedRowData["1 Kreis Va"],
                                                                                selectedRowData["2 Kreis Va"],
                                                                                selectedRowData["VA"],
                                                                                selectedRowData["1 Kreis DL-5"],
                                                                                selectedRowData["2 Kreis DL-5"],
                                                                                selectedRowData["DL-5"],
                                                                                selectedRowData["DL-10"],
                                                                                selectedRowData["DL-tech"],
                                                                                selectedRowData["CO2"],
                                                                                selectedRowData["H2"],
                                                                                selectedRowData["He"],
                                                                                selectedRowData["He-RF"],
                                                                                selectedRowData["Ar"],
                                                                                selectedRowData["N2"],
                                                                                selectedRowData["NGA"],
                                                                                selectedRowData["N2O"],
                                                                                selectedRowData["AV"],
                                                                                selectedRowData["SV"],
                                                                                selectedRowData["ZSV"],
                                                                                selectedRowData["USV"],
                                                                                selectedRowData["IT Anbindung"],
                                                                                selectedRowData["Anwendungsgruppe"],
                                                                                selectedRowData["Allgemeine Hygieneklasse"],
                                                                                selectedRowData["Raumhoehe"],
                                                                                selectedRowData["Raumhoehe 2"],
                                                                                selectedRowData["Belichtungsfläche"],
                                                                                selectedRowData["Umfang"],
                                                                                selectedRowData["Volumen"],
                                                                                selectedRowData["ET_Anschlussleistung_W"],
                                                                                selectedRowData["HT_Waermeabgabe_W"],
                                                                                selectedRowData["VEXAT_Zone"],
                                                                                selectedRowData["HT_Abluft_Vakuumpumpe"],
                                                                                selectedRowData["HT_Abluft_Schweissabsaugung_Stk"],
                                                                                selectedRowData["HT_Abluft_Esse_Stk"],
                                                                                selectedRowData["HT_Abluft_Rauchgasabzug_Stk"],
                                                                                selectedRowData["HT_Abluft_Digestorium_Stk"],
                                                                                selectedRowData["HT_Punktabsaugung_Stk"],
                                                                                selectedRowData["HT_Abluft_Sicherheitsschrank_Unterbau_Stk"],
                                                                                selectedRowData["HT_Abluft_Sicherheitsschrank_Stk"],
                                                                                selectedRowData["HT_Spuele_Stk"],
                                                                                selectedRowData["HT_Kühlwasser"],
                                                                                selectedRowData["O2_Mangel"],
                                                                                selectedRowData["CO2_Melder"],
                                                                                selectedRowData["ET_RJ45-Ports"],
                                                                                selectedRowData["ET_64A_3Phasig_Einzelanschluss"],
                                                                                selectedRowData["ET_32A_3Phasig_Einzelanschluss"],
                                                                                selectedRowData["ET_16A_3Phasig_Einzelanschluss"],
                                                                                selectedRowData["ET_Digestorium_MSR_230V_SV_Stk"],
                                                                                selectedRowData["ET_5x10mm2_Digestorium_Stk"],
                                                                                selectedRowData["ET_5x10mm2_USV_Stk"],
                                                                                selectedRowData["ET_5x10mm2_SV_Stk"],
                                                                                selectedRowData["ET_5x10mm2_AV_Stk"],
                                                                                selectedRowData["Wasser Qual 3 l/min"],
                                                                                selectedRowData["Wasser Qual 2 l/Tag"],
                                                                                selectedRowData["Wasser Qual 1 l/Tag"],
                                                                                selectedRowData["Wasser Qual 3"],
                                                                                selectedRowData["Wasser Qual 2"],
                                                                                selectedRowData["Wasser Qual 1"],
                                                                                selectedRowData["LHe"],
                                                                                selectedRowData["LN l/Tag"],
                                                                                selectedRowData["LN"],
                                                                                selectedRowData["N2 Reinheit"],
                                                                                selectedRowData["N2 l/min"],
                                                                                selectedRowData["Ar Reinheit"],
                                                                                selectedRowData["Ar l/min"],
                                                                                selectedRowData["He Reinheit"],
                                                                                selectedRowData["He l/min"],
                                                                                selectedRowData["H2 Reinheit"],
                                                                                selectedRowData["H2 l/min"],
                                                                                selectedRowData["DL ISO 8573"],
                                                                                selectedRowData["DL l/min"],
                                                                                selectedRowData["VA l/min"],
                                                                                selectedRowData["CO2 l/min"],
                                                                                selectedRowData["CO2 Reinheit"],
                                                                                selectedRowData["O2 l/min"],
                                                                                selectedRowData["O2 l/min"],
                                                                                selectedRowData["O2 Reinheit"],
                                                                                selectedRowData["Laserklasse"]
                                                                                );