<?php
$formFields = [
    ["type" => "text", "name" => "roomname", "label" => "Raumname", "required" => true],
    ["type" => "text", "name" => "username", "label" => "Username", "required" => true],

    ["type" => "yesno", "name" => "fussboden_onorm_b5220", "label" => "Fußboden ÖNORM B5220"],
    ["type" => "yesno", "name" => "verdunkelung", "label" => "Verdunkelung"],
    ["type" => "yesno", "name" => "schallschutzanforderung", "label" => "Erhöhte Schallschutzanforderung"],
    ["type" => "select", "name" => "vc_klasse", "label" => "VC-Klassen", "options" => ["0" => "keine Anforderung", "1" => "Klasse 1", "2" => "Klasse 2", "3" => "Klasse 3"]],
    ["type" => "yesno", "name" => "chemikalienliste", "label" => "Chemikalienliste"],
    ["type" => "select", "name" => "vexat_zone", "label" => "VEXAT Zone", "options" => ["0" => "Zone 0", "1" => "Zone 1", "2" => "Zone 2"]],
    ["type" => "select", "name" => "bsl_level", "label" => "Biosafety Level (BSL)", "options" => ["0" => "Nein", "1" => "Ja"]],
    ["type" => "yesno", "name" => "laser", "label" => "Laser"],
    ["type" => "yesno", "name" => "o2", "label" => "O2"],
    ["type" => "yesno", "name" => "va", "label" => "VA"],
    ["type" => "yesno", "name" => "dl", "label" => "DL"],
    ["type" => "yesno", "name" => "co2", "label" => "CO2"],
    ["type" => "yesno", "name" => "h2", "label" => "H2"],
    ["type" => "yesno", "name" => "he", "label" => "He"],
    ["type" => "yesno", "name" => "he_rf", "label" => "He-RF"],
    ["type" => "yesno", "name" => "ar", "label" => "Ar"],
    ["type" => "yesno", "name" => "n2", "label" => "N2"],
    ["type" => "yesno", "name" => "ln", "label" => "LN"],
    ["type" => "text", "name" => "spezialgas", "label" => "Spezialgas lt. Anwender"],
    ["type" => "yesno", "name" => "sv_geraete", "label" => "SV versorgte Geräte"],
    ["type" => "yesno", "name" => "usv_geraete", "label" => "USV versorgte Geräte"],
    ["type" => "yesno", "name" => "alarm_glt", "label" => "Alarmaufschaltung auf Gebäudeleittechnik"],
    ["type" => "yesno", "name" => "kuehlwasser", "label" => "Kühlwasser"],
    ["type" => "yesno", "name" => "wasserq3", "label" => "Wasserqualität 3"],
    ["type" => "yesno", "name" => "wasserq2", "label" => "Wasserqualität 2"],
    ["type" => "yesno", "name" => "wasserq1", "label" => "Wasserqualität 1"],
    ["type" => "yesno", "name" => "geraete_abfluss", "label" => "Geräte mit Wasserabflüssen"],
    ["type" => "yesno", "name" => "punktabsaugung", "label" => "Punktabsaugung vorhanden"],
    ["type" => "yesno", "name" => "abluft_sicherheitsschrank", "label" => "Abluft Sicherheitsschrank vorhanden"],
    ["type" => "yesno", "name" => "abluft_vakuumpumpe", "label" => "Abluft Vakuumpumpe vorhanden"],
    ["type" => "yesno", "name" => "abrauchabzuege", "label" => "Abrauchabzüge/Veraschung"],
    ["type" => "yesno", "name" => "sonderabluft", "label" => "Sonderabluft vorhanden"],
    ["type" => "text", "name" => "raumnr", "label" => "Raumnr"],
    ["type" => "text", "name" => "raumbereich_nutzer", "label" => "Raumbereich Nutzer"],
    ["type" => "text", "name" => "ebene", "label" => "Ebene"],
    ["type" => "text", "name" => "nf", "label" => "NF"]
    // Add more fields as necessary using same pattern
];