CREATE TABLE room_requirements (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    roomname VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,


    fussboden_onorm_b5220 TINYINT,
    verdunkelung TINYINT,
    schallschutzanforderung TINYINT,
    vc_klasse TINYINT,
    chemikalienliste TINYINT,
    vexat_zone ENUM('0','1','2'),
    bsl_level VARCHAR(32),
    laser TINYINT,
    o2 TINYINT,
    va TINYINT,
    dl TINYINT,
    co2 TINYINT,
    h2 TINYINT,
    he TINYINT,
    he_rf TINYINT,
    ar TINYINT,
    n2 TINYINT,
    ln TINYINT,
    spezialgas VARCHAR(255),
    sv_geraete TINYINT,
    usv_geraete TINYINT,
    alarm_glt TINYINT,
    kuehlwasser TINYINT,
    wasserq3 TINYINT,
    wasserq2 TINYINT,
    wasserq1 TINYINT,
    geraete_abfluss TINYINT,
    punktabsaugung TINYINT,
    abluft_sicherheitsschrank TINYINT,
    abluft_vakuumpumpe TINYINT,
    abrauchabzuege TINYINT,
    sonderabluft TINYINT,
    gasart VARCHAR(255),
    bsl_klasse VARCHAR(32),
    leistung_w INT,
    lmin INT,
    ltag2 INT,
    ltag1 INT,

    -- General fields
    raumnr VARCHAR(255),
    raumbereich_nutzer VARCHAR(255),
    ebene VARCHAR(255),
    nf VARCHAR(255)
);
